version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv  # Exclude virtualenv from host
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  frontend-dev:
    build:
      context: ./frontend
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000  # For dev outside Docker
      - CHOKIDAR_USEPOLLING=true  # Better file watching in Docker
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge